/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/main/': RouteRecordInfo<'/main/', '/main', Record<never, never>, Record<never, never>>,
    '/main/components/BannerSection': RouteRecordInfo<'/main/components/BannerSection', '/main/components/BannerSection', Record<never, never>, Record<never, never>>,
    '/main/components/Business': RouteRecordInfo<'/main/components/Business', '/main/components/Business', Record<never, never>, Record<never, never>>,
    '/main/components/Map': RouteRecordInfo<'/main/components/Map', '/main/components/Map', Record<never, never>, Record<never, never>>,
    '/main/components/Partners': RouteRecordInfo<'/main/components/Partners', '/main/components/Partners', Record<never, never>, Record<never, never>>,
    '/main/components/question': RouteRecordInfo<'/main/components/question', '/main/components/question', Record<never, never>, Record<never, never>>,
    '/main/components/Services': RouteRecordInfo<'/main/components/Services', '/main/components/Services', Record<never, never>, Record<never, never>>,
    '/main/components/Why': RouteRecordInfo<'/main/components/Why', '/main/components/Why', Record<never, never>, Record<never, never>>,
  }
}
